services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always

  redis:
    image: redis:latest
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always

  airflow-init:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    profiles: ["init"]
    restart: "no"
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create --username $${_AIRFLOW_WWW_USER_USERNAME} --password $${_AIRFLOW_WWW_USER_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com || true
      "
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "30"
      
    command: ["airflow", "scheduler"]
    restart: always
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  airflow-triggerer:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    command: ["airflow", "triggerer"]
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    command: ["airflow", "webserver"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD","curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  airflow-worker:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__WORKER_CONCURRENCY: "4"
    command: ["airflow", "celery", "worker"]
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  flower:
    image: ${AIRFLOW_IMAGE}
    pull_policy: always
    environment:
      PYTHONPATH: /opt/airflow
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET: ${GCS_BUCKET}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","project_id":"${GCP_PROJECT_ID}"}'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    command: ["airflow", "celery", "flower"]
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

##volumes:
##  postgres-db-volume:
